### ISSUE TITLE
Address is not reloaded when clicking a link in the transaction table

### ISSUE THREAD

**Issue by Cremba** [zenprotocol/explorer#11]
to recreate: 

go to any address page
click one link in the transaction table

you will see the transaction table is loading and then show a new list of transactions
but there is not loading in the address table, the only things that change are the transaction amount.

reload the page and you will see the actual address table

**Comment by liorfrenkel** [comment]
@Cremba - several addresses can have the same transactions, and this is what is happening here.
in an address page, click on another address and then compare several transactions in the list.
please check again? thanks

**Comment by liorfrenkel** [comment]
Fixed with 0b23e152618d5683d9c039bc8fc938bda1cd337a
