### ISSUE TITLE
Transaction are missing

### ISSUE THREAD

**Issue by Cremba** [zenprotocol/explorer#13]
in the [address](https://zp-explorer-staging.herokuapp.com/address/zen1qk02q3j43zaxa4vvrrc3dkzenvq3xpmk77y6c3ywn66qrum7l0asqv74w6l) it supposedly has 3 transactions, but only the third transaction is shown
[First Transaction](https://zp-explorer-staging.herokuapp.com/tx/27b310dbfaafedf53ccd0b70e8dfc9cff653dcedbd49fa2b6a6ed4ef3a087119)
[Second Transaction](https://zp-explorer-staging.herokuapp.com/tx/b18df42aec6e8451535256397db407f4512f82e330973bb0da5fc9b86014b6dc)
[Third Transaction](https://zp-explorer-staging.herokuapp.com/tx/c260c9b6da57a4035a1fb101eed9b6047ac61ad1a90d585d1aec2f8b4501773b)

if you go the address page you will see three transactions in the address table, if you scroll down up to the loading gif and scroll back up you will see transaction = 1.

**Comment by liorfrenkel** [comment]
Problem was adding the transactions for an address from the same block - 
the db transaction was not supplied to `addressesDAL.findByAddress()`, hence it could not be found.
