### ISSUE TITLE
[Feature Request] Add Timestamp Column on transaction details when viewing an address on explorer

### ISSUE THREAD

**Issue by thecryptochef** [zenprotocol/explorer#18]
While viewing an address in the explorer, have an extra column for "timestamp"

![screenshot_22](https://user-images.githubusercontent.com/42422018/44180309-85f93900-a0f3-11e8-9d31-582a00571a98.png)

**Comment by elanperach** [comment]
Done.

https://zp.io/address/zen1qsap3rkrvl6ckfj0nsztxalcfh9gsuzt5ndcgh9nq03tx9ygxdsvshgeter
